#!/usr/bin/env python
from PyQt4 import QtCore, QtGui
from PyQt4.QtCore import *; 
from PyQt4.QtGui import *;
import sys

class MyWindow(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setWindowTitle('qmavstatus')
	self.gridlayout = QtGui.QGridLayout() 
        self.resize(600,200)    
	labelInfo = QtGui.QLabel( "labelInfo" )
        labelInfo.setText("Hello" )
        self.gridlayout.addWidget(labelInfo, 0,0,1,1)


        self.setLayout(self.gridlayout)
 
if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    mywindow = MyWindow() 
    mywindow.show()
    app.exec_()
