(cl:defpackage mavros-msg
  (:use )
  (:export
   "<STATE>"
   "STATE"
   "<BATTERYSTATUS>"
   "BATTERYSTATUS"
   "<WAYPOINT>"
   "WAYPOINT"
   "<MAVLINK>"
   "MAVLINK"
   "<RCIN>"
   "RCIN"
   "<FILEENTRY>"
   "FILEENTRY"
   "<WAYPOINTLIST>"
   "WAYPOINTLIST"
   "<ACTUATORCONTROL>"
   "ACTUATORCONTROL"
   "<VFR_HUD>"
   "VFR_HUD"
   "<OVERRIDERCIN>"
   "OVERRIDERCIN"
   "<CONTROL_REFS>"
   "CONTROL_REFS"
   "<RADIOSTATUS>"
   "RADIOSTATUS"
   "<RCOUT>"
   "RCOUT"
  ))

